sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - rpm
install:
  - git clone --branch 2.4 --depth=1 --no-single-branch https://github.com/Graylog2/graylog2-server ../graylog2-server
  - (cd ../graylog2-server && mvn -DskipTests=true compile -B -V)
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dskip.web.build=true -B -V
script:
  - mvn package -B
before_deploy:
  - mvn jdeb:jdeb && export RELEASE_DEB_FILE=$(ls target/*.deb)
  - mvn rpm:rpm && export RELEASE_RPM_FILE=$(find target/ -name '*.rpm' | tail -1)
  - rm -f target/original-*.jar
  - export RELEASE_PKG_FILE=$(ls target/*.jar)
  - echo "Deploying release to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: iivsZR0icrOmJW54q4XsAFEwNG/DKy2INui0AHfN3OsL8mwEEJ6DZAyyy0LOMJQYPJ+5Cl8Twu9pkeojA3UxhVjoiKM0nhv0po5BAWeY4N6pNvW9+sEyAmH5kJ/v/yl0ffdnMrLl1elJH0oaTSnbGSb1LpGhJ2J1PsTe2O+XMV5yKURsR9SLhUW1nIrHkMaH960jQSqpVGzlWG863doqJit41//V1OytD5eeda3s/1MRlQ9BbJs1phaE7zBEbrSEhBlmPbEuOyHIQbZUpG6WY12wnHXAyFkyjo+eKCpvBoXYIfGQS8P+mPBSUvtY0jWh+IV/VYXaZZiA9bhh1WLUFKkm3lDVdj9X/omYzJOB0xAvubFUJBQSaF8DGf9uZ/0396dUo/MHhgO3Q7W/JXH1//K7SG4ODzBP22PetI9nPkunQDwm0HhvMufhNKcDwKfN9j57F1F/nggECXpUK/ADHWt0Hy/shSmJsdLNF8WR5SK8Dg8i7NrTuFy/ePyDUJOJ69JYLYJYHovxKShXTP2q+bvcK+T40KdNX32dV275DItjm8mZRB80jk+Yga0mwt+D5SpMWCnufP9hcS6KZuHqGZxpHuZvYwv3DWu+n3F8Qvg1qB1wPStfGJ9stdnZy8Q+x7t49uqMqrMN/f13roTNpkJmN8ZXOTZYguTWbgYue/c=
  file:
    - "${RELEASE_PKG_FILE}"
    - "${RELEASE_DEB_FILE}"
    - "${RELEASE_RPM_FILE}"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8
    repo: ahus1/graylog-plugin-auth-sso
